### ISSUE TITLE
The RSS links on the sitemap do not work.

### ISSUE THREAD

**Issue by tsukemono2** [zwagoth/e621ng#312]
When following either the comments or forum RSS links in https://e621.net/static/site_map, they go a 403 page.

**Comment by Earlopain** [comment]
This seems to simply be blocked at the web server level, on my development instance both work fine.
The error message is from when the codebase got updated to a newer version of danbooru. If this doesn't work anymore since then maybe it should just be removed.

**Comment by bitWolfy** [comment]
Frankly, I wonder if anyone ever used these RSS feeds at all.
Posts I understand. Forum topics, on the other hand...

**Comment by kiranoot** [comment]
These links and the accompanying code are slated for removal.

**Comment by Earlopain** [comment]
Removed with https://github.com/zwagoth/e621ng/commit/d9f7bec1eede6bb13292fedd831d427e134aa7b8, https://github.com/zwagoth/e621ng/commit/776c4ad6d9c47cee5afe99d3e219c2e6015508d0, https://github.com/zwagoth/e621ng/commit/7b3077e3483ee7152ad8043caa3578329406f7a3 and https://github.com/zwagoth/e621ng/commit/852141a2dd476c4530b4d340aadec45af548d103

Post sets and individual forum topics also had their atom feeds removed.
