### ISSUE TITLE
Using an invalid image URL in the upload form produces a broken image preview

### ISSUE THREAD

**Issue by bitWolfy** [zwagoth/e621ng#322]
This is not as obvious as it seems, as the broken preview image is different from the one supplied in the URL.

For example: https://e621.net/uploads/new?upload_url=https://i.imgur.com/foo.jpg
The site tries to display https://e621.net/images/notfound-preview.png in the preview section, which does not exist.

Mind you, this image file does not seem to exist in danbooru either.
I've no idea where it came from, or where did it go.

**Comment by Earlopain** [comment]
Fixed with https://github.com/zwagoth/e621ng/commit/b02a52a30b5f8f47e35643ad8ccd889ed50c9213
