### ISSUE TITLE
Application Not Working After Install

### ISSUE THREAD

**Issue by DonovanDMC** [zwagoth/e621ng#323]
This is directly after running `vagrant up`, not having done anything else
I have all of the plugins for vagrant, and the extension pack for virtualbox installed
no matter how many times I reinstall, change computers, etc I cannot get this to work

it's always the same thing:
![](https://butts-are.cool/chrome_09-30-2021_12-40-43.png)

The only log I could easily find was at [/vagrant/log/development.log](https://pastebin.com/6DH23Bwg)
I haven't included the install log, as my terminal scrolled past the majority of it. I can take it down if needed

I've tried running this on two Windows 10 personal computers, got this same message on both
I've also tried on some other servers (Ubuntu (16.04 & 20.04) and Debian (8 & 10)) but haven't been able to even get close to this point (stuck somewhere in installing, I forget where).

At this rate, I don't really care about getting it working on Ubuntu, I just want it on my Windows pc for local testing

**Comment by kiranoot** [comment]
Run `bundle install` and then `yarn install` on the target machine under the install folder(/vagrant/ by default) and then restart the e621 service with `sudo service danbooru restart` this should allow it to automatically build the manifest using the new version of webpacker.

If you are still having problems with it, make sure to clear the public/packs folder or at least delete the manifest.json from it so that it will try to build it again.

**Comment by DonovanDMC** [comment]
![](https://butts-are.cool/PUTTY_09-30-2021_14-25-21.png)

Seems like ruby somehow isn't installed

I installed the bundler exactly as it says there, and it's giving me this when building
![](https://butts-are.cool/PUTTY_09-30-2021_14-29-40.png)

**Comment by Earlopain** [comment]
The ruby install is local to the user, in this case `danbooru`. It won't be visible to root.  You should automatically log in as that when running `vagrant ssh`.

**Comment by DonovanDMC** [comment]
`vagrant ssh` fixed the ruby issue, `bundle install` worked fine, but getting this with `yarn install`
![](https://butts-are.cool/WindowsTerminal_09-30-2021_14-32-43.png)

**Comment by kiranoot** [comment]
This whole webpacker business has been such a disastrous chore of teething issues.

The production machines are running nodejs 14 now, so it should be a matter of getting the right apt package paths going and then updating nodejs to resolve that.

It seems like you're running a really old version of the install script or have a really old version of the install, as the install script is set up to install node 14 in the repo.

**Comment by DonovanDMC** [comment]
I cloned the repo today, I've deleted and recloned several times, so there's no way what I have is outdated

I'll go run it all again just in case

**Comment by Earlopain** [comment]
If you could attach the setup log of that in case it still does not work would be very helpful.

Edit: Did you maybe already set this up some time ago and kept the vm around? In that case an older version of node might habe been added and you would need to manually update the source.

**Comment by kiranoot** [comment]
Check /etc/apt/sources.list.d/nodesource.list it should list deb.nodesource.com/node_14.x as a source, if it is not present or lists a different version then something very curious has gone wrong.

**Comment by DonovanDMC** [comment]
> If you could attach the setup log of that in case it still does not work would be very helpful.
> 
> Edit: Did you maybe already set this up some time ago and kept the vm around? In that case an older version of node might habe been added and you would need to manually update the source.

I've never tried to setup this
if I had, it would have been last year, and I've only had this pc for 2 months
and I delete the vm each time I reinstall
I'm currently waiting for a reinstall to finish

**Comment by DonovanDMC** [comment]
I couldn't get the terminal output to write to a file, but I did notice that `/etc/apt/sources.list.d/nodesource.list` doesn't exist, and it's still `v10.19.0` after a reinstall
![](https://butts-are.cool/WindowsTerminal_09-30-2021_16-05-22.png)

I looked for what repository is supplying it, and apparently it's `http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages`
![](https://butts-are.cool/WindowsTerminal_09-30-2021_16-08-11.png)

**Comment by DonovanDMC** [comment]
Looked up a way to find what repository supplied a package, and apparently it's `http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages`
![](https://butts-are.cool/WindowsTerminal_09-30-2021_16-08-11.png)

**Comment by Earlopain** [comment]
This is the default version provided by ubuntu.
Executing `vagrant provision > log.txt 2>&1` should write the output to a file. `provision` executes the script again without needing to destroy the vm and downloading the updates again. Remove the currectly installed node version before that though since it doesn't try to add the correct repository otherwise.

**Comment by DonovanDMC** [comment]
I've reran it again and got a log for both this time (I ran `apt remove nodejs` after the install, unsure of what else to do as I never really need to remove packages)
[[vagrant up log](https://pastebin.com/uzXYRtJL)] [[vagrant provision log](https://pastebin.com/WAv3ZsX9)]

**Comment by DonovanDMC** [comment]
I can't even install node myself because apt-get update fails when trying to update `https://apt.postgresql.org/pub/repos/apt focal-pgdg Release`

> (...)
> Ign:8 https://apt.postgresql.org/pub/repos/apt focal-pgdg InRelease
Err:9 https://apt.postgresql.org/pub/repos/apt focal-pgdg Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 217.196.149.55 443]
Reading package lists... Done
E: The repository 'https://apt.postgresql.org/pub/repos/apt focal-pgdg Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Error executing command, exiting

Trying to manually install nodejs after changing that to http just gives more of the same errors
I don't believe both (or even either) are expired, so something funky is happening here
> Err:10 https://deb.nodesource.com/node_14.x focal Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 104.93.21.26 443]
Reading package lists... Done
E: The repository 'https://deb.nodesource.com/node_14.x focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://apt.postgresql.org/pub/repos/apt focal-pgdg InRelease' doesn't support architecture 'i386'
Error executing command, exiting

**Comment by Earlopain** [comment]
Nothing we can do about that. This seems to be a general problem: https://github.com/nodesource/distributions/issues/1266
You just chose an unfortunate timing window to try set this up. There probably is a workaround in that issue you can try, but I didn't look too much into it.

**Comment by DonovanDMC** [comment]
I just realized why
The Let's Encrypt R3 intermediate expired yesterday 

I really did chose the worst time, it expired the EXACT day I tried this
(I didn't mention that I got it to work *once*, which was on the 29th, might have lead to this outcome quicker)
I was able to install node after updating `ca-certificates` (`sudo apt install ca-certificates` is what I ran)

**Comment by DonovanDMC** [comment]
even after updating node, I'm still having issues
`yarn install` is failing for a different reason now
![](https://butts-are.cool/WindowsTerminal_10-01-2021_07-23-56.png)

The message on the page is still exactly the same
![](https://butts-are.cool/chrome_10-01-2021_07-24-35.png)

**Comment by bitWolfy** [comment]
I had the same issue. This error happens because symlinks are not enabled by default on the guest machine.
Try the solution listed here:
https://speich.net/articles/en/2018/12/24/virtualbox-6-how-to-enable-symlinks-in-a-linux-guest-os/

Alternatively, Kira recommended setting that parameter via the vagrantfile, like so:
```
config.vm.provider :virtualbox do |vm|
    vm.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
end
```

If neither of those solutions work, there is a slightly dodgy workaround.
Just run `yarn install` in the shared folder on the host machine's side. It'll work.

**Comment by DonovanDMC** [comment]
Installing from the host side was the only one that seemed to work, haven't thoroughly tested but this is the first time I've been able to see the front page in days
![](https://butts-are.cool/chrome_10-02-2021_07-10-42.png)

**Comment by Earlopain** [comment]
Glad to see you were able to get it up and running. I'll investigate a bit why the vagrantfile did not correctly set the symlink permissions. It should already do that but it doesn't look like that is working very well.

**Comment by bitWolfy** [comment]
Congratulations! I'm glad you managed to get it to work.

**Comment by Earlopain** [comment]
I added the fix/workaround for the symlinks to the readme. I'll leave this one open until the other issue with installing node is resolved on their end.

**Comment by DonovanDMC** [comment]
This isn't really related to the application not working, but I can't figure out how to do a few things (like turning off test mode {I've tried changing the env in a few places (like adding `, env: { "RAILS_ENV" (and ENV & ENVIRONMENT) => "production" }` to the provision line), haven't gotten it to work yet}, rebuilding the code without deleting recreating everything)

I assume there just isn't a wiki for this stuff, as I can't find one, and couldn't find any on Danbooru's side either

I couldn't really see any place in the Discord to ask about this stuff

I'm currently trying to modify this into an application for my own uses (image api primarily, using this for letting other people add suggestions 'n' stuff) so not being able to find this stuff is kind of detrimental to my use of this, and searching through code for hours is getting really old

**Comment by Earlopain** [comment]
I can't really help you with that. I only do development and never tried putting it in production mode myself. The Vagrantfile also isn't really made for that, the setup it does is specific for development workflows and doesn't take security too seriously. If you want to go production it is more of a thing you can use as a blueprint to setup your own server.

I can try to help you to the best of my knowledge though:
- If  you are still using the stock `danbooru` service the `Procfile` is responsible for  starting the rails server, `RAILS_ENV` needs to be set to `production` there, or `-e production` passed. I'm not sure which of those version would work, maybe they both do.
- You will probably need to create the database yourself, `bundle exec rake db:setup` with `RAILS_ENV` should do the trick.
- You will need to precompile the webpacker resources with `bundle exec rake assets:precompile`

I didn't try this myself but hopefully this gives you some useful pointers. There are probably a few more things to do but running a rails app in production mode isn't specific to e6 so you should fine plenty of resources about that on the web.

**Comment by DonovanDMC** [comment]
~~It seems I've gotten myself in a bit over my head with what I'm trying to do here, as I got completely lost once again for several hours~~

~~I don't want to waste any more of your time with this, so I'll just move on for now and go back to that later, and back to what I was originally doing (making a npm module)~~

Seems I'm actually finally getting somewhere with modifying the `vagrant/install.sh` script to work with docker

~~Failbooru for me 😔~~
![](https://butts-are.cool/PUTTY_10-06-2021_03-14-08.png)

16 hours later, and I finally have it working, thank you guys for your help (took another 21 hours {after those 16} to get the db working again, but that's besides the point)
![](https://butts-are.cool/chrome_10-13-2021_06-35-29.png)

**Comment by Earlopain** [comment]
I went ahead and added a workaround since there still hasn't been a new vagrant box release, who know how long that could take.
