### ISSUE TITLE
Inconsistent BUR/alias permissions for rejecting own request

### ISSUE THREAD

**Issue by ShadyGuy123** [zwagoth/e621ng#354]
Right now Members can reject their own BURs, but not their alias/implication requests.  
This could be clearer, so either disallow rejecting own BURs allow rejecting alias/implication requests, or mention the difference to [e621:accounts](https://e621.net/wiki_pages/2423)  

I'd vote for allowing rejecting own requests, so admins wouldn't have as much work to do

**Comment by Earlopain** [comment]
Members can reject their own alias/implications for a few months now, I just didn't know/forgot about this issue. See pr #429
