### ISSUE TITLE
Add warnings on report pages

### ISSUE THREAD

**Issue by Lance-Armstrong** [zwagoth/e621ng#360]
Scary warning boxes could be added on report pages in certain cases to cut down the number of duplicate and unnecessary tickets.

Here are three conditions that should trigger a warning:

1. The comment, forum post, or blip has already been reported by another user. The warning could also indicate when the content was last reported and link to the ticket.

- If the content has been edited by the user who posted it (not an admin) more recently than the latest ticket about the content, a warning should not be displayed on the report page.

2. The comment, forum post, or blip being reported is old. IIRC, no action is taken against minor offenses that are older than 1 month, and Abuse of Site Tools lists "Reporting forum posts, threads, comments, blips, or any other site media that is older than 6 months" as a violation.

- A clarification can be added to permit reporting of malicious links, or other qualifying serious infractions.
- Edited content could reset the clock. So if a comment was posted 9 months ago but edited 5 days ago, no warning is displayed when reporting it.

3. The comment, forum post, or blip was made by a currently permanently banned user.

Users should not be prevented from reporting content since there could be malicious links or other reasons to report such as commendation.

1 and 3 could be given a less serious (e.g. yellow instead of red) warning box since neither is against the rules. 2 can be split into two levels: older than 1 month (less serious), older than 6 months (more serious).

**Comment by Earlopain** [comment]
I wanted to add the first point a while ago and it was rejected for reasons you can read about in the comment from Kira: https://github.com/zwagoth/e621ng/pull/304#issuecomment-898970960

> ... I am rejecting this as duplicates are primarily a concern for administration handling tickets and not users filing reports ... Internally there are benefits for allowing duplicates like this.

I also don't know what to think of the other two points. Most tickets are about recent content, well within the allowed timerange. Closing invalid tickets does not take much time. 
Perhaps the note which is always displayed can be extended to include the 6 month timeframe, regardless of how old the content actually is.

What do you think about this @zwagoth?

**Comment by Earlopain** [comment]
I'll close this, #588 seems pretty close
