### ISSUE TITLE
DText and old links for sets are broken

### ISSUE THREAD

**Issue by Lance-Armstrong** [zwagoth/e621ng#361]
`set #1484` DText links to https://e621.net/sets/1484 which shows "Not found."

The correct link is https://e621.net/post_sets/1484

Older set links that were once valid are also broken
https://e621.net/posts/779838#comment-2265476
https://e621.net/posts/1016944#comment-2844633

The format used to be: https://e621.net/set/show/1484

The link on the [Help: DText](https://e621.net/help/dtext) page is also incorrect, although `set #1234` does not exist anyway.

**Comment by Earlopain** [comment]
I am attempting to fix this in https://github.com/zwagoth/dtext_rb/pull/2, though that has been sitting over there for a while now.

**Comment by Earlopain** [comment]
PR was merged and is now live.
