### ISSUE TITLE
Rating locks don't create ModActions

### ISSUE THREAD

**Issue by Earlopain** [zwagoth/e621ng#362]
> Is rating locking visible via mod actions? Unless it's restricted I haven't seen any recently, and the ones I can see are from [March 2020](https://e621.net/mod_actions?commit=Search&search%5Baction%5D=post_rating_lock)

_Originally posted by @DonovanDMC in https://github.com/zwagoth/e621ng/issues/346#issuecomment-1001806269_

https://github.com/zwagoth/e621ng/blob/e2a86cd38a164134d0364fd34a52c917316ef30a/app/models/post.rb#L36
https://github.com/zwagoth/e621ng/blob/e2a86cd38a164134d0364fd34a52c917316ef30a/app/models/post.rb#L1995-L1997
It's supposed to happend but doesn't.

**Comment by kiranoot** [comment]
This is a result of the _changed? flags being reset after save, it should be saved_change_to_field?
