### ISSUE TITLE
e621ng_e621_1 keeps exiting in docker and localhost shows 'Failbooru'

### ISSUE THREAD

**Issue by SnakerBone** [zwagoth/e621ng#365]
**Logs message:**
04:41:10 unicorn | 'bin/rails server -p 9000 -b 0.0.0.0' started with pid 12

04:41:10 jobs | 'bundle exec sidekiq -c 1 -q low_prio -q tags -q default -q high_prio -q video' started with pid 18

04:41:16 jobs | bundler: failed to load command: sidekiq (/usr/local/bundle/bin/sidekiq)

04:41:16 jobs | LoadError: cannot load such file -- /app/config/danbooru_local_config

04:41:16 jobs |   /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'

04:41:16 jobs |   /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'

04:41:16 jobs |   /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'

04:41:16 jobs |   /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'

04:41:16 jobs |   /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'

04:41:16 jobs |   /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'

04:41:16 jobs |   /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'

04:41:16 jobs |   /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'

04:41:16 jobs |   /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `require_relative'

04:41:16 jobs |   /app/config/application.rb:18:in `<top (required)>'

04:41:16 jobs |   /app/config/environment.rb:2:in `require_relative'

04:41:16 jobs |   /app/config/environment.rb:2:in `<top (required)>'

04:41:16 jobs |   /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'

04:41:16 jobs |   /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'

04:41:16 jobs |   /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'

04:41:16 jobs |   /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'

04:41:16 jobs |   /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/cli.rb:273:in `boot_application'

04:41:16 jobs |   /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/cli.rb:37:in `run'

04:41:16 jobs |   /usr/local/bundle/gems/sidekiq-6.3.1/bin/sidekiq:31:in `<top (required)>'

04:41:16 jobs |   /usr/local/bundle/bin/sidekiq:23:in `load'

04:41:16 jobs |   /usr/local/bundle/bin/sidekiq:23:in `<top (required)>'

04:41:17 unicorn | /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- /app/config/danbooru_local_config (LoadError)

04:41:17 unicorn |  from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'

04:41:17 unicorn |  from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'

04:41:17 unicorn |  from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'

04:41:17 unicorn |  from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'

04:41:17 unicorn |  from /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'

04:41:17 unicorn |  from /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'

04:41:17 unicorn |  from /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'

04:41:17 unicorn |  from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `require_relative'

04:41:17 unicorn |  from /app/config/application.rb:18:in `<main>'

04:41:17 unicorn |  from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'

04:41:17 unicorn |  from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'

04:41:17 unicorn |  from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'

04:41:17 unicorn |  from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'

04:41:17 unicorn |  from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'

04:41:17 unicorn |  from /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'

04:41:17 unicorn |  from /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'

04:41:17 unicorn |  from /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'

04:41:17 unicorn |  from /usr/local/bundle/gems/railties-6.1.4.4/lib/rails/commands/server/server_command.rb:138:in `block in perform'

04:41:17 unicorn |  from /usr/local/bundle/gems/railties-6.1.4.4/lib/rails/commands/server/server_command.rb:135:in `tap'

04:41:17 unicorn |  from /usr/local/bundle/gems/railties-6.1.4.4/lib/rails/commands/server/server_command.rb:135:in `perform'

04:41:17 unicorn |  from /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'

04:41:17 unicorn |  from /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'

04:41:17 unicorn |  from /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'

04:41:17 unicorn |  from /usr/local/bundle/gems/railties-6.1.4.4/lib/rails/command/base.rb:69:in `perform'

04:41:17 unicorn |  from /usr/local/bundle/gems/railties-6.1.4.4/lib/rails/command.rb:48:in `invoke'

04:41:17 unicorn |  from /usr/local/bundle/gems/railties-6.1.4.4/lib/rails/commands.rb:18:in `<main>'

04:41:17 unicorn |  from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'

04:41:17 unicorn |  from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'

04:41:17 unicorn |  from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'

04:41:17 unicorn |  from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'

04:41:17 unicorn |  from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'

04:41:17 unicorn |  from bin/rails:4:in `<main>'

Am I missing something or is this a bug? If its not a bug how do I fix it??

**Comment by DonovanDMC** [comment]
> LoadError: cannot load such file -- /app/config/danbooru_local_config

Did you run the initial setup? This sounds like you didn't


Failbooru is the generic 500 (server) error page


Also, it's better to post error on pastebin or something similar, as walls of text make things hard to navigate *especially on mobile*

Also I'm not part of this project, so if you have ran the initial setup, I can't really help you much further, you'll have to wait for Kira or Earlopain 

Though I would recommend deleting (`docker-compose down --rmi "all" --remove-orphans` should do the trick, this will delete all current data) and restarting from scratch, if you run the setup and it still doesn't work

**Comment by SnakerBone** [comment]
Thank you, this worked.

**Comment by faucetlol** [comment]
> Though I would recommend deleting (`docker-compose down --rmi "all" --remove-orphans` should do the trick, this will delete all current data) and restarting from scratch, if you run the setup and it still doesn't work

I'd nearly given up trying to get my dev environment to work, but this managed to get it working again. Thanks Donovan :)

It might even be worth including this in the troubleshooting section.

**Comment by Earlopain** [comment]
Maybe you didn't `docker-compose build` since the gemfile was last changed? Without an error trace it's imposible to tell.

Also, I think `docker-compose down -v` should be enough, as you don't need to rebuild the images. Just removing the volumes while I was experimenting with creating the dockerfile was fine. After that you can run the commands in the readme again, as if you'd run them for the first time.
