### ISSUE TITLE
Missing Replacement hourly limit in users/upload_limit

### ISSUE THREAD

**Issue by ShadyGuy123** [zwagoth/e621ng#379]
https://e621.net/users/upload_limit shows the user's current upload limits, including hourly uploads and tag edits, but not hourly replacements.
As far as I can tell this is a fixed 10 but I'm not sure.

**Comment by Earlopain** [comment]
Yeah, the limit is 10 per hour, controlled with https://github.com/zwagoth/e621ng/blob/ac1286fe5a76a2356572a25a648a1bbee6ef6ec5/config/danbooru_default_config.rb#L266. While replacements aren't technically uploads it would make sense to show it there anyways.

Note to self: Change throttle ignore from `can_approve_posts` to `can_upload_free?`?

**Comment by Earlopain** [comment]
I kind of dodged the issue here. In the near future replacements adhere to the same limits as your normal uploads.
