### ISSUE TITLE
BUR category change erroring when tag doesn't exist

### ISSUE THREAD

**Issue by DonovanDMC** [zwagoth/e621ng#380]
I've attempted to use a BUR on my own instance to bulk update category tags, and keep getting this same error (the error snippet below was retrieved from an unmodified dev instance). This only happens when the tag doesn't exist, which I get why this happens, but a message instead of an outright error would be more favorable (or even creating the tag if it doesn't exist).

```
undefined method `category=' for nil:NilClass
app/logical/alias_and_implication_importer.rb:259:in `block (2 levels) in execute'
app/logical/alias_and_implication_importer.rb:234:in `map'
app/logical/alias_and_implication_importer.rb:234:in `block in execute'
app/logical/alias_and_implication_importer.rb:233:in `execute'
app/logical/alias_and_implication_importer.rb:16:in `process!'
app/models/bulk_update_request.rb:112:in `block (2 levels) in approve!'
app/logical/current_user.rb:10:in `scoped'
app/models/bulk_update_request.rb:111:in `block in approve!'
app/models/bulk_update_request.rb:110:in `approve!'
app/controllers/bulk_update_requests_controller.rb:37:in `approve'
```

https://github.com/zwagoth/e621ng/blob/ac1286fe5a76a2356572a25a648a1bbee6ef6ec5/app/logical/alias_and_implication_importer.rb#L257-L260

**Comment by Earlopain** [comment]
I will prevent creation when the tag doesn't already exist. It doesn't make sense to change the category when the tag has never been used before. It's convenient for your own instances but is most likely an user-error on e6.

**Comment by DonovanDMC** [comment]
> I will prevent creation when the tag doesn't already exist. It doesn't make sense to change the category when the tag has never been used before. It's convenient for your own instances but is most likely an user-error on e6.

This is about what I expected, I wouldn't really want that on my own instance tbh - very easy to cause a mess
