### ISSUE TITLE
Query about API access from github action

### ISSUE THREAD

**Issue by Deer-Spangle** [zwagoth/e621ng#389]
Hey there,

I've got some integration/system tests which run nightly on one of my projects, which hit the live e621 API, and probably make 4 or 5 requests a night. they have a little wait between requests, etc. (Most my tests do not hit the live e621 API, but I like to have some system level tests which do, just to ensure e621 API format doesn't to change without warning)
It seems like more often than not, at least one of these requests will fail with a 500 error or time out. The tests seem to pass and be stable when running locally.
Are there some restrictions about API requests coming from github actions workers? Or should I just be adding more retry handling and longer timeouts?

**Comment by kiranoot** [comment]
I would need more details about what endpoints you are hitting, and which ones fail to investigate this further. Please send additional details in an email to kira at e621.net so that I can investigate further. No intentional limitations have been put in place for github actions.
