### ISSUE TITLE
Stats isn't themed

### ISSUE THREAD

**Issue by faucetlol** [zwagoth/e621ng#408]
![image](https://user-images.githubusercontent.com/102884856/168414978-c625c0e8-bff4-4fbd-aec7-6ff753e1d306.png)

Stats shows as default blue even when using a theme - I was going to tackle this one myself but couldn't work out how to get the stats page working on my own instance.

**Comment by Earlopain** [comment]
Some things like updating stats are run daily, but I don't think dev is doing that at the moment. Prod probably has that in a crontab somewhere, but you can run it manually with `bin/rails maintenance:daily`

The styling for that page is currently in a style tag, you will need to move that into a seperate .scss file for theming to be possible.

**Comment by Earlopain** [comment]
@faucetlol2 do you plan on fixing this? There are a few other things I want to clean up on the stats page, but I can wait a bit if you want to close this first.

**Comment by faucetlol** [comment]
> @faucetlol2 do you plan on fixing this? There are a few other things I want to clean up on the stats page, but I can wait a bit if you want to close this first.

Sorry, got busy with work and pushed it to the side until the weekend, but might make some time to finish it today.

**Comment by Earlopain** [comment]
It's all good, just wanted to know if anything will happen. Take your time, it's no hurry
