### ISSUE TITLE
API: Ability to batch get tag aliases or convert queries.

### ISSUE THREAD

**Issue by Deer-Spangle** [zwagoth/e621ng#419]
Hey there, got [an issue over here at the e621 python lib repo](https://github.com/PatriotRossii/e621-py/issues/4) where we've been considering what would be needed for blacklists to be converted to their aliased forms.
Naiive solution is fetching the whole tag alias list and doing it client side, but that's ~700 queries, and a lot of data to hold. Not a great solution. Certainly not something they can add to the lib at startup!

So there seem to be two decent solutions in my eyes:
1) Adding a batch get endpoint, or an ability to specify multiple IDs in the search endpoint, ([which would need implementing here, I think](https://github.com/zwagoth/e621ng/blob/1c61801bebefaf86d1065586393b8a793cb60e2e/app/models/tag_relationship.rb#L124))
2) Exposing [this `TagAlias.to_aliased_query(query)`](https://github.com/zwagoth/e621ng/blob/1c51a354848d46a84d8771b97fbf69a46c204374/app/models/tag_alias.rb#L92) method in a new endpoint? Maybe something like `tag_aliases.json:convertQuery?query=-deer` or something. I'm not sure whether the e621 controller architecture allows for endpoints of that form.

I'm happy to make a PR trying to implement one of these if you prefer, just a bit unsure which is more idiomatic for the project

**Comment by faucetlol** [comment]
I think what you want is already available, the `antecedent_name` can be comma separated to bulk search aliases. [Example](https://e621.net/tag_aliases.json?commit=Search&search%5Bantecedent_name%5D=cat,dog,pig)

**Comment by Earlopain** [comment]
You can also use the `seach[id]` parameter, which works on basically all endpoints. [Example](https://e621.net/tag_aliases.json?commit=Search&search[id]=17819,18310,18579). Since this works on all models it is implemented in the base class, there's a limit of 100 ids at once. https://github.com/zwagoth/e621ng/blob/1c51a354848d46a84d8771b97fbf69a46c204374/app/models/application_record.rb#L127.

**Comment by Hmiku8338** [comment]
Thanks for such quick and helpful replies!

**Comment by Deer-Spangle** [comment]
Ooooh, fascinating, thank you! I had definitely missed both of those options, interesting! That may be helpful in other areas of the API too then!
