### ISSUE TITLE
Upload Whitelists isn't on the sitemap

### ISSUE THREAD

**Issue by faucetlol** [zwagoth/e621ng#420]
The [Upload Whitelists](https://e621.net/upload_whitelists) page does not appear on the sitemap, making it difficult to find the page.

Would've made a PR but didn't know what category it would fit under the best.

**Comment by faucetlol** [comment]
Possibly also worth including a link to https://e621.net/forum_topics/22269 somewhere on the page - possibly in the secondary menu?

**Comment by Earlopain** [comment]
It's actually in the sitemap already, though apparently admin only or something. It's in the admin section, feel free to just move it out of the permission check there.

Sure, adding the request thread in the secondary links sounds good.

**Comment by faucetlol** [comment]
Oh, I wasn't expecting it to be admin only so I didn't bother checking the code, thanks for letting me know :)

PR coming soon!

**Comment by faucetlol** [comment]
I'm not sure how to link to the forum post in the subnav, `forum_topics_path(id: 22269)` leads to `/forum_topics?id=22269` rather than `/forum_topics/22269` - is this just a constraint of the path?

**Comment by Earlopain** [comment]
I'm not at my computer right now, but I think this is something I constantly fall for myself. You are using plural for the method, so it generates a link for the index. Try the singular instead, like `forum_topic_path(22269)`

**Comment by faucetlol** [comment]
Perfect, that was exactly what I needed to do! Is there anywhere I can actually see where all these paths are defined?

**Comment by Earlopain** [comment]
Sure there is, these methods are getting defined through rails magic in [config/routes.rb](https://github.com/zwagoth/e621ng/blob/master/config/routes.rb). Though what you asked for is probably `bin/rails routes`, which prints all the available routes in a more easily digestable format.
