### ISSUE TITLE
"Blank" page for client-side userscripts?

### ISSUE THREAD

**Issue by VariableVixen** [zwagoth/e621ng#435]
This is an unconventional request, I know, but as the developer for the sizable [en621 (enhanced e621)](https://github.com/PrincessRTFM/WebUtil/blob/master/js/monkey/en621.user.js) userscript, it would be nice if there was a way for me to access an effectively empty skeleton page, one that matches the style of the rest of the site, for the purpose of presenting script users with settings and the like. As it is now, if I want to do such a thing, I need to either hijack a 404 page or create some kind of overlay on existing pages.

As an example, a `/empty` or `/blank` page could be used by scripts, checking the page anchor to avoid conflicts. Scripts would then be responsible for directing users to that page with the appropriate anchor, such as `/blank#en621/main` for my own script.

**Comment by faucetlol** [comment]
One example I've already seen of this is [Idem's Sourcing Suite](https://github.com/Sasquire/Idems-Sourcing-Suite), which hijacks a 404 page at `/extensions`

**Comment by Earlopain** [comment]
I agree with faucet that the simplest solution would be to hijack a 404 page. Insert css like `#page > p { display: none; }` when on your custom extension page to hide the message and add your content after.
