### ISSUE TITLE
The `page` option breaks on post_versions after 10,000 most recent entries

### ISSUE THREAD

**Issue by DonovanDMC** [zwagoth/e621ng#437]
Attempting to view any pages that stretch beyond the 10,000 most recent entries (134 with the default 75, 501 with 20) results in an error. Paginating via the `a` & `b` syntax works fine.

#### Works
[[75]: Page 133](https://e621.net/post_versions?page=133&limit=75)
[[20]: Page 500](https://e621.net/post_versions?page=500&limit=20)

#### Does not work
[[75]: Page 134](https://e621.net/post_versions?page=134&limit=75)
[[20]: Page 501](https://e621.net/post_versions?page=501&limit=20)

Other things I've tested work all the way up to the standard 750, even with a `320` limit, which is the 240,000 most recent.

**Comment by Earlopain** [comment]
Elasticsearch by default has a limit of 10.000. Posts have this limit increased and it works perfectly fine fo some reason, but when I asked Kira to increase it for post versions too a while back they reverted it instantly because of performance issues.

Only posts and post versions use elasticsearch, everything else goes directly to the database.

**Comment by DonovanDMC** [comment]
I figured as much, I'm sure it's a pain in the ass to traverse some 30 million entries 🙃 (31.5 million by id)

It would be nice to have some kind of notice instead of an error with no information, if possible

**Comment by Lance-Armstrong** [comment]
I just encountered this. The site shouldn't allow you to navigate to pages 134 through 750 if they are going to cause an error 100% of the time.

The user could edit the URL to get to those pages, and see either the error or a custom notice.

**Comment by Earlopain** [comment]
It's not trivial to just change the number of displayed pages. The page number depends on the users limit setting, and there is no connection between the pagination code and the code displaying the actual page numbers.

Fixing this properly requires more effort than I'm willing to commit at the moment. I'm fine with catching the error instead like Donovan suggested.

**Comment by kiranoot** [comment]
It might be possible to statically provide a count parameter to the paginator so it won't display too many pages.

https://github.com/zwagoth/e621ng/blob/master/app/logical/danbooru/paginator/base_extension.rb#L61

The search_count param allows for lying to the paginator for how many final results exist.

**Comment by Earlopain** [comment]
The `search_count` parameter is a shitty name, since it is only used to display the maximum amount of pages when it is truthy.

But it might actually be usable like this as well, with a few tweaks. I haven't though about using it like that, good idea.

**Comment by kiranoot** [comment]
Whoops, not search_count, but the count param. My mistake. I picked the wrong one in my head when trying to explain it.

**Comment by Earlopain** [comment]
Yeah, I saw that too, but glossed over it. I think there will still need to be a few more changes, since it looks like it will always use the count parameter, even when there are fewer results. I haven't tested it yet, it might just work. That would be nice.

**Comment by Earlopain** [comment]
> I haven't tested it yet, it might just work. That would be nice.

_It didn't_

Post versions will now only show as many pages as you can actually use, and switch to sequential navigation afterwards. <sup>Let's hope I didn't break something completly unrelated with this change</sup>
