### ISSUE TITLE
Trying to add a post to a full set using a tag edit causes an unexpected error

### ISSUE THREAD

**Issue by faucetlol** [zwagoth/e621ng#438]
I often add posts to sets using the `set:` metatag while editing the tags, which is a little faster than navigating the usual "Add to set" UI. 

One of my sets recently reached the limit of 10,000 posts and attempting to add a post to that set using tag edits causes the page to load for a long time, before producing an unexpected error. Adding it the normal way results in the expected `Error: Sets can have up to 10,000 posts each` so it just seems like the metatag way just isn't expecting the error.

`2dd35052-97ba-4023-8fc5-16f379ecd994` is a log ID of one of the errors if that's helpful in any way.

**Comment by Sindrake** [comment]
Fixed in #669.
