### ISSUE TITLE
Add Reasonable Limits To Artist Fields

### ISSUE THREAD

**Issue by DonovanDMC** [zwagoth/e621ng#444]
Most things around e621 have relatively sensible limits, I've tried just filling artists with a lot of bullshit data on a local instance, and almost every single test passed. The only ones that failed were to be expected (new user & blocked/anon).
![image](https://user-images.githubusercontent.com/17226394/198880990-5b427f5e-ffe4-492d-94ab-9e545a3287e1.png)

![image](https://user-images.githubusercontent.com/17226394/198881190-0e8302fd-214f-4442-802b-217f371249aa.png)

As far as I can tell, most these will accept any arbitrary amount of data. The biggest issue I was running into was either request size (100MB), statement timeout (9 seconds), or index size being too large. The only fields that seem to be limited are `group_name` (limited to 100), the amount of urls (limited to 25, the extra there is counting an empty newline), and the length of urls (which looks to be 4096, I barely missed it).

These huge entries also broke my local e621 instance. I had to remove the artist entries to be able to load anything. The most prevalent error was an index error, which makes it seem like it was behind on requests and still trying to catch up on requests that had been canceled ages ago.
![image](https://user-images.githubusercontent.com/17226394/198882417-1d3836f9-06f5-444f-9a5f-e74bda1df655.png)

**Comment by DonovanDMC** [comment]
Here's the [json](https://butts-are.cool/tmp/artist-40.json) of the massive artist, if you want that for some reason

And if you're interested in what it looked like in the ui
<img src="https://user-images.githubusercontent.com/17226394/198883124-8628ce5e-0588-4b81-b34a-a705073a3a06.png" width="33%"><img src="https://user-images.githubusercontent.com/17226394/198883047-316a8963-3606-45ac-b896-e54ce4178dbf.png" width="33%"><img src="https://user-images.githubusercontent.com/17226394/198883062-77bb064a-bbfc-4529-9818-d5c466000bad.png" width="33%">

**Comment by Earlopain** [comment]
Thanks for reporting, but please disclose issues like this privately in the future, since it's an easy DoS attack

**Comment by DonovanDMC** [comment]
Shit sorry, I didn't even think about that
I'll keep that in mind in the future, I've never ran across bugs like this inside codebases that weren't mine 😓

Looking at the commit you may have forgotten notes

**Comment by Earlopain** [comment]
In testing you are able to submit long notes, but they aren't actually persisted. You just don't get the proper error message. Wiki pages have a limit of 250_000 characters I believe

**Comment by DonovanDMC** [comment]
Ah right, I forgot that's just chucked off to a wiki page
sorry again for the panic I probably caused there 🙃

**Comment by Earlopain** [comment]
It's fine, don't worry about it
