### ISSUE TITLE
Former Staff And Below Cannot Create Collection Pools With >30 Posts

### ISSUE THREAD

**Issue by DonovanDMC** [zwagoth/e621ng#450]
As the title says. When creating a pool with >30 posts, and `category` set to **collection**, anyone former staff and below is presented with the following error:
```javascript
// 422 Unprocessable Entity
{
  "errors": {
    "base": [
      "You cannot change the category of pools with greater than 30 posts"
    ]
  }
}
```

**series**/providing nothing works just fine

Also, sidenote: Are invalid posts meant to be allowed in pools? Through local testing, I was able to put invalid post ids into a pool, even with a basic `Member` user.

I am running all of this with throttles disabled, if that makes a difference.

**Comment by Earlopain** [comment]
> Also, sidenote: Are invalid posts meant to be allowed in pools? Through local testing, I was able to put invalid post ids into a pool, even with a basic `Member` user.

I'm aware that this is something you can do, but haven't looked further into it since doesn't seem to make trouble

**Comment by DonovanDMC** [comment]
Should I open an issue about it to keep it on the docket, or just leave it be? I figured it was "intentional" as checking is probably more of a hassle than it's worth most of the time, though I assumed when requesting pools that posts would be validated at some point. I'll have to correct that assumption.

**Comment by Earlopain** [comment]
Sure, make an issue. Why not.
