### ISSUE TITLE
Additional validations surrounding user time zone.

### ISSUE THREAD

**Issue by kiranoot** [zwagoth/e621ng#461]
It is currently possible to provide values for time zone that Rails doesn't recognize, which has serious side effects for the user that provides these invalid items.

Additional validation of the time zone field is needed before saving the value.

**Comment by Earlopain** [comment]
Are there any matches for `SELECT COUNT(*) FROM users WHERE time_zone LIKE '%/%'`? There are two formats timezones can be represented in, and both are equally valid to rails. which are valid. `Arizona` <=> `America/Phoenix`.

The former is in use now, but I want to know if the other one was used as well, before making the validation too strict.

**Comment by kiranoot** [comment]
There are zero results for that format. I think just testing it by trying to set it should be enough, and catching the exception blocks the edit.
