### ISSUE TITLE
Locked Notice Always Shows

### ISSUE THREAD

**Issue by DonovanDMC** [zwagoth/e621ng#462]
I'm sure this is a well known issue, but I've finally decided to bring it up as it's annoying me a bit.
Simply:
* Add a locked tag to a post
* In a separate edit, add or remove a tag
* Observe the `Forcefully added {n} locked tag(s)` notice

**Comment by faucetlol** [comment]
I can't actually seem to replicate this on my own instance, though I've definitely seen it happen quite a few times on e621. I followed the steps but the only time I got the notice was when adding the locked tag itself.

**Comment by DonovanDMC** [comment]
You are correct, the exact steps I originally followed aren't reproducing that
I'd imagine that's why this has been around for so long, it's hard to reliably reproduce

**Comment by Earlopain** [comment]
I'm pretty sure this was because you edited a post with c/dnp on it, that exhibits the same behaviour.

**Comment by DonovanDMC** [comment]
That makes sense, I'd imagine whichever post had been pulled down had a dnp on it
