### ISSUE TITLE
Pool Versions With Null updater_id Error

### ISSUE THREAD

**Issue by DonovanDMC** [zwagoth/e621ng#471]
While looking through the autogenerated pools (created via `newpool:`, as you do) I stumbled across one that randomly errored, I can't really tell why it's erroring, but it's only erroring on its first version.

The pool is [#1059](https://e621.net/pools/1059)
Visiting any pool versions releted to this pool where the first version would be shown will error, as can be shown by [this](https://e621.net/pool_versions?search%5Bpool_id%5D=1059), and [this](https://e621.net/pool_versions?limit=1&page=11&search%5Bpool_id%5D=1059), the latter of which specifically goes for `limit=1&page=11` to only show the first version. Each other version works as they should.

This pool and its versions are from the time where there are nulls everywhere (2011), so I'm not really sure if this is even worth worrying about, but since it has an exception and not just nulls everywhere I figured I'd make an issue for it. I'd look into it myself but I can't really tell what's happening with it.

Also a side note, the pool versions show that pool is locked, despite seemingly anyone being able to edit it. (I haven't tested editing it myself, but the most recent edit of 7 days ago was by a normal user)

**Comment by faucetlol** [comment]
When the view is rendered a null for `updater_id` causes an exception when `link_to_user` gets called without a user id, you can actually see the data just fine by using the JSON endpoint.

Interestingly enough there's already checks for this in the code that aren't working:
https://github.com/e621ng/e621ng/blob/f6b53dd0d32ce9206cf8978f3c58a7323945145b/app/views/pool_versions/_standard_listing.html.erb#L24-L26
https://github.com/e621ng/e621ng/blob/f6b53dd0d32ce9206cf8978f3c58a7323945145b/app/views/pool_versions/_revert_listing.html.erb#L27-L29

**Comment by DonovanDMC** [comment]
Reproduced it locally finally, it's rails throwing up an error
![image](https://user-images.githubusercontent.com/17226394/218413511-0cc3813c-3645-4cc4-bc33-b6d4f5ea419c.png)

So it's coming from here:
https://github.com/e621ng/e621ng/blob/a5df59da89122a5ef21f55e6481e15d9fd8292ba/app/models/pool_version.rb#L103-L105

Updater being called anywhere is the issue. Adding `return nil if updater_id.nil?` inside the updater method seems to remedy the issue.

**Comment by DonovanDMC** [comment]
I've made #472, which adds `return nil if updater_id.nil?` before the User.find call. As far as I can tell locally, this should fix the issue

**Comment by Earlopain** [comment]
I filled the few cases where this is null with user id 1 so this is no longer needed. There were about 40 or so.
