### ISSUE TITLE
Dtext list grievances 

### ISSUE THREAD

**Issue by Earlopain** [zwagoth/e621ng#487]
```
[section]
* A
[/section]
[section]
B
* C
[/section]
```
results in

```html
<div class="styled-dtext">
   <div class="expandable expanded">
      <div class="expandable-header"><span class="section-arrow"></span></div>
      <div class="expandable-content" style="display: block;">
         <ul>
            <li>A<br></li>
         </ul>
      </div>
   </div>
   <div class="expandable expanded">
      <div class="expandable-header"><span class="section-arrow"></span></div>
      <div class="expandable-content" style="display: block;">
         <p>B</p>
         <li>C<br></li>
      </div>
   </div>
</div>
```

Adding a newline before `C` or removing the previous section makes the other section generate with `ul` again.

**Comment by Earlopain** [comment]
This leaves a hanging [/quote] at the end:
```
[quote]
[section]
* test
[/section]
[/quote]
```
This doesn't:
```
[quote]
[section]
* test

[/section]
[/quote]
```

**Comment by Earlopain** [comment]
Color when you'r no longer staff messes with the lists as well, see changelog thread

**Comment by Earlopain** [comment]
```
* list
h3. Header
```
This will definitely not create a header.

**Comment by faucetlol** [comment]
Similar to the quote example, this also leaves a trailing [/section]

```
[section]
[section=Subsection]
* Item 1
* Item 2
[/section]
[/section]
```

Originally pointed out in [topic #35760](https://e621.net/forum_topics/35760), I planned on making a GitHub issue but I guess I forgot.

**Comment by Earlopain** [comment]
I'm thinking this is one of those where you fix one all the others fall into place as well. They all have lists and whitespace in common, which makes me me just a tad hopeful.

**Comment by Earlopain** [comment]
I took a look at this. Danbooru figured this one out already https://github.com/danbooru/dtext_rb/commit/285e40127891a9077a0f3ef8225fb601ed79c9e9

Unforunatly the codebase has diverged significantly and I can't just copy this over. I'm not knowledgable enough about Ragel to come up with my own solution. Oh how I wish we'd just use markdown.

**Comment by Earlopain** [comment]
I started importing commits from the danbooru repo: https://github.com/e621ng/dtext_rb/tree/danbooru-catchup

It will still take me a while to go through everything, but hopefully I'll come to a point where I can easily copy their fix. Looks like there will also be some other nice changes along the way, like moving to C++.

I grabbed a copy of all the publicly available dtext to compare my output against to hopefully prevent making incompatible/wrong changes.
