### ISSUE TITLE
[ModActions] Inconsistencies and Issues

### ISSUE THREAD

**Issue by DonovanDMC** [zwagoth/e621ng#488]
<details>
<summary><code><strike>artist_page_rename</strike></code></summary>
When renaming an artist, the new name is shown on both sides, making it look like nothing actually happened.

![image](https://user-images.githubusercontent.com/17226394/226681894-61c8622f-d98a-44be-b741-837dfa8329ec.png)
</details>

<details>
<summary><code><strike>artist_user_unlinked</strike></code></summary>

The `artist_user_unlinked` modactions do not display a user like they should.

![image](https://user-images.githubusercontent.com/17226394/226817956-d60fe096-164f-4347-b6b7-309f894aab84.png)
![image](https://user-images.githubusercontent.com/17226394/226817970-b74758d3-39d0-4139-9369-2753781a09da.png)
</details>

<details>
<summary><code>forum_topic_update</code></summary>

`forum_topic_update` is in the search dropdown, but it seems completely unused. In my mind this should be shown when the name of a forum topic is changed, since stick and lock have their own actions, but I can't see anything logged when the name is changed. As far as I can tell (aka I looked at the first commit it appeared in and called it a day), it's been unused since it was introduced in ca5b0d5f807152ad2b2c37f9fa8d7892c25f43e3.
</details>

<details>
<summary><code>report_reason_update</code></summary>

Only the reason is logged in the modactions, which hides changes to the description, making it look like nothing happened.
![image](https://user-images.githubusercontent.com/17226394/226819127-6f4b4401-32ca-4969-a9cb-495854ba5074.png)
</details>

<details>
<summary><code>user_feedback_update</code></summary>

The `user_feedback_update` does not show if the type of record (positive/negative/neutral) was changed, it only shows the reason, regardless if it was changed. (as can be seen. It *does* log the new type of record, but doesn't say the previous type or call out the changes)

![image](https://user-images.githubusercontent.com/17226394/226830425-2a08add3-0078-4715-b691-abbb7eadf4e7.png)
</details>

<details>
<summary><code><strike>wiki_page_undelete</strike></code></summary>

Since dc3fa7fd3459f9723472a9901b6e4d006749a30e, deleting a wiki page fully destroys the wiki page, and none of these entries seem to exist, thus making this action irrelevant.
</details>

**Comment by DonovanDMC** [comment]
Turns out I'm just an idiot on thinking extraneous actions are created, I expected to rename to show up visually in the artist versions but it doesn't, there's just a sudden shift in the name shown on the left. The same name being shown on both sides is definitely a thing, though

**Comment by faucetlol** [comment]
It seems to be writing it wrong into the database, I renamed an artist to "newname" and the result saved into the database was `{"new_name":"newname","old_name":"newname"}`.

https://github.com/e621ng/e621ng/blob/aedea618dc6b3b74757f8286cf69681009fc31bc/app/models/artist.rb#L35-L37

Maybe I'm missing something, but `name_was` doesn't actually seem to be defined anywhere.

**Comment by Earlopain** [comment]
The `_was` methods are rails magic. https://api.rubyonrails.org/classes/ActiveModel/Dirty.html

Based on that this seemed to have worked some time in the past I'm putting blame on this commit:
https://github.com/e621ng/e621ng/commit/4dfd8f41c30605284d883b300a598c94783e47bb

Notice how I changed when the callback gets executed but didn't touch the value being logged. It should probably be `name_before_last_save` instead.

**Comment by faucetlol** [comment]
Not sure I'll ever be able to wrap my head around all this rails magic, but it's interesting to learn about at the least. `name_before_last_save` does indeed seem to do the correct thing. There's also a `linked_user_id_was` in there that probably needs changing too.

**Comment by DonovanDMC** [comment]
Things like this are one of the reasons I really hate ruby and subsequently rails. Methods are so obscure and loosely defined that you can't hardly tell if what you're doing is working, or will continue working in the future. I say this coming from several strictly typed languages, which I'm very used to.

**Comment by DonovanDMC** [comment]
> Not sure I'll ever be able to wrap my head around all this rails magic, but it's interesting to learn about at the least. `name_before_last_save` does indeed seem to do the correct thing. There's also a `linked_user_id_was` in there that probably needs changing too.

I was just looking around the mod actions and noticed something weird around all of the currently existing unlinking actions, they're all missing a user
![image](https://user-images.githubusercontent.com/17226394/226803669-3c0113f3-e348-4314-8ce3-91f4e064f6f6.png)
![image](https://user-images.githubusercontent.com/17226394/226803688-19b146b0-f207-4e4b-8882-d8f5b57bf691.png)

This sounds like an issue that could stem from the usage of `_was`

**Comment by DonovanDMC** [comment]
Looks like I'm doing what I always do, taking one simple thing and applying a shit ton of scope creep. It's what I do best.

**Comment by Earlopain** [comment]
I fixed the artist ones and removed references to the wiki undeletion, don't feel like doing the rest right now.
