### ISSUE TITLE
[HelpPages] JSON response errors when no help pages exist

### ISSUE THREAD

**Issue by DonovanDMC** [zwagoth/e621ng#492]
![image](https://user-images.githubusercontent.com/17226394/227357250-b0e4083f-b0dd-409f-a6bf-df6e9e74659b.png)

~~Deleted help pages are also not removed from the cache when they are deleted, so they hang around for 12 hours, or until another help page is created/edited. To be specific, they still show on the index page.~~

~~Deleting a wiki page that's being used by a help page will cause an error to be shown on that help page. This is somewhat expected, but something should probably either prevent this, or also delete the help page.~~
![image](https://user-images.githubusercontent.com/17226394/230527925-07ee8a7f-d39d-470d-b051-0ecd65be973d.png)

**Comment by Earlopain** [comment]
Fix two things, left the index unexpected error for sometime else. It's probably the same issue as with all the other endpoints where this happens.

**Comment by DonovanDMC** [comment]
I did want to ask, in the future would you prefer I group things like this, or make a separate issue for each?

**Comment by Earlopain** [comment]
Single issues seem preferable to me

**Comment by DonovanDMC** [comment]
👍 I never know, I didn't want to spam issues just in case

**Comment by DonovanDMC** [comment]
> Fix two things, left the index unexpected error for sometime else. It's probably the same issue as with all the other endpoints where this happens.

I've definitely seen this in a few other places, namely the `alt_list` route of the `admin/users` controller iirc

And a more real world example, `/comments.json?group_by=post` - exact same error
