### ISSUE TITLE
Creating a new prefixed tag with tag edit gives `Repopulated 1 old tag` warning

### ISSUE THREAD

**Issue by faucetlol** [zwagoth/e621ng#494]
Using a tag edit to create a new tag with a prefix results in a repopulated old tag warning, even if it has never been used before. For example, adding `character:nonexistentcharacter123` to a post with a tag edit results in `Repopulated 1 old tag: nonexistentcharacter123` - even though the tag has definitely never been used before.

I do believe this has been a known issue for quite a while, but it's popped up on the forums a few times recently and noticed there isn't a GitHub issue for it yet.
* [topic #36248](https://e621.net/forum_topics/36248)
* [topic #37778](https://e621.net/forum_topics/37778)

**Comment by DonovanDMC** [comment]
This has definitely been around for a long time, like #462 

I'd imagine it never really annoyed anyone (that actually knew where to report issues) enough to report it
