### ISSUE TITLE
Images are not displayed

### ISSUE THREAD

**Issue by weisseskopfadler1** [zwagoth/e621ng#500]
Images are not displayed in the chrome browser. How to solve this problem?

**Comment by DonovanDMC** [comment]
Hard refresh (CTRL+SHIFT+R) or otherwise clear your cache and try again

**Comment by weisseskopfadler1** [comment]
> Жесткое обновление (CTRL+SHIFT+R) или иным образом очистите кеш и повторите попытку.

Does not help. Same thing on the phone.

**Comment by faucetlol** [comment]
If you're trying to access the instance from a different device than it's hosted on, you'll need to change `DANBOORU_HOSTNAME` to whatever hostname you're accessing it from rather than localhost.

https://github.com/e621ng/e621ng/blob/22ae2f6bc4b7aeb223bdbb4ab18e57c754260022/docker-compose.yml#L4
