### ISSUE TITLE
Viewing Artist Versions Requires Authentication

### ISSUE THREAD

**Issue by DonovanDMC** [zwagoth/e621ng#504]
As the title says. Fetching `/artist_versions` requires authentication for seemingly no reason. As far as I can see, no other version types require this. 
https://github.com/e621ng/e621ng/blob/179bb69f1da33de904cc9c0788e4db3a2fc5ac54/app/controllers/artist_versions_controller.rb#L2-L2

**Comment by faucetlol** [comment]
This was the same for a few other things until db225c59ed010df6bfe226fca64bc5b4494382f9

**Comment by DonovanDMC** [comment]
I figured it was something forgotten, I've known of it for a while but I'm only just now really going back through what I've written down for e621's api and bringing up weird things I've noticed
