### ISSUE TITLE
Modification Routes Error With No Auth

### ISSUE THREAD

**Issue by DonovanDMC** [zwagoth/e621ng#509]
When using JSON, if no auth is provided, an empty error is returned. The error is for a missing CSRF token. CSRF tokens shouldn't be checked on api requests at all, since they should never be present.

```json
{
    "success": false,
    "message": "An unexpected error occurred.",
    "code": null
}
```
![image](https://user-images.githubusercontent.com/17226394/232851590-7c290724-d5dd-47e1-b1bb-026312a3494d.png)

**Comment by Earlopain** [comment]
I'm not seeing why this should be any different than all other pages. Could you give it a try with removing the `detect_xhr` `before_action` in the controller?

**Comment by DonovanDMC** [comment]
Same issue with that removed

**Comment by Earlopain** [comment]
Eh, alright. I'll take a look at this when I get rid of the old iqdb implementation, or give this a shot yourself (if you want)

**Comment by faucetlol** [comment]
Works just fine with a GET request, however.

**Comment by DonovanDMC** [comment]
Well, I have figured it out. This *does* happen in the other routes, `POST /wiki_pages.json` and `POST /uploads.json` for example, routes I tested and saw the same. So it's more, csrf being checked if api authentication isn't present, even if the response format is json. If the CSRF check didn't happen, the expected Access Denied response would be returned (on other routes, you'd get through fine here)

**Comment by DonovanDMC** [comment]
Though IQDB specifically, I'm seeing a plain `null` returned when not providing any parameters. That's probably something that should be changed to the relevant format for each, or return an error.

**Comment by DonovanDMC** [comment]
> Works just fine with a GET request, however.

CSRF protection is disabled for GET requests.

**Comment by Earlopain** [comment]
I don't really feel like touching this:
https://github.com/e621ng/e621ng/blob/edae5a6b777e394eae41b8d08c4c30af525c3542/app/controllers/application_controller.rb#L5

The easiest solution to me is changing the error from unexpetect to expected with som nice message:
https://github.com/e621ng/e621ng/blob/edae5a6b777e394eae41b8d08c4c30af525c3542/app/controllers/application_controller.rb#L68-L69

**Comment by DonovanDMC** [comment]
> I don't really feel like touching this:

I really don't blame you there

> The easiest solution to me is changing the error from unexpetect to expected with som nice message:

Having a proper error message there would be nice, so we at least know what's happening

**Comment by DonovanDMC** [comment]
Though for IQDB specifically, is there really a reason for it to have csrf protection? I'm sure it's a default of forms and not a deliberate decision, but surely it could be disabled on that route. I can't see any reason for it to require csrf protection besides maybe mitigating spam by unauthenticatrd users, and that's shaky at best.

**Comment by Earlopain** [comment]
IQDB is already rate limited to 1 request every 2 seconds for everyone. This endpoint really should be `GET` but you must also be able to upload files. There should be something I can use to skip CSRF per controller. Just putting `skip_forgery_protection` in it seems like it should do the job just fine

**Comment by DonovanDMC** [comment]
> This endpoint really should be `GET` but you must also be able to upload files.

I honestly didn't even know it could be a get until faucet mentioned it. I was specifically uploading a file though when testing.
