### ISSUE TITLE
Final tag preview is case sensitive

### ISSUE THREAD

**Issue by faucetlol** [zwagoth/e621ng#510]
![IMG_20230424_093354_414](https://user-images.githubusercontent.com/102884856/233943046-39f7d0f6-bf0c-4dbe-a5d5-84f5cd06534e.jpg)

Only shows tag relations for lowercase tags. A little annoying on mobile where autocorrect likes to randomly capitalise words sometimes.

**Comment by faucetlol** [comment]
https://github.com/e621ng/e621ng/blob/edae5a6b777e394eae41b8d08c4c30af525c3542/app/models/tag.rb#L308-L311

I tried changing this to `query.to_s.unicode_normalize(:nfc).downcase.gsub(/\u3000/, " ").strip` and this seems like a good solution, but not really sure how to check if this messes with anything else. (Not really sure when a tag would ever _not_ need to be downcased... but maybe there's some weird edge cases)

A safer alternative could just be changing `scan_tags(tags)` to `scan_tags(tags.downcase)` here

https://github.com/e621ng/e621ng/blob/edae5a6b777e394eae41b8d08c4c30af525c3542/app/logical/tags_preview.rb#L1-L7

I've also got another commit ready (https://github.com/faucetlol2/e621ng/commit/2312f76bd9ce705849fc61bbc7e1b3732c9a1598) to make the tag relationship search case-insensitive too, and could just bundle these into one PR.

**Comment by Sindrake** [comment]
Properly fixed in d235ce223fc9c35621d7ce1d9a810b9268f5f160, actually.
