### ISSUE TITLE
Hotdog users can't see removed tags on post versions

### ISSUE THREAD

**Issue by faucetlol** [zwagoth/e621ng#511]
![IMG_20230424_085924_862](https://user-images.githubusercontent.com/102884856/233940752-cef84a36-e68c-41f9-bb70-3a06fcaafe16.jpg)

Either the same shade of red as the background, or similar enough that I can't see it.

Though, anybody consistently using that theme will probably lose their ability to use their eyes soon enough.

**Comment by Earlopain** [comment]
This theme is a meme, I'm not going to inveset time fixing it. The post versions page is the least of it's problems. Like you said, it's your own fault if you're using it.
