### ISSUE TITLE
Remove/disable/implement the unimplemented search tools from autocomplete 

### ISSUE THREAD

**Issue by mm12** [zwagoth/e621ng#523]
IN: https://github.com/e621ng/e621ng/blob/master/app/javascript/src/javascripts/autocomplete.js.erb#L97
see also:
https://github.com/e621ng/e621ng/blob/master/app/logical/elastic_post_query_builder.rb#L474 
https://github.com/e621ng/e621ng/blob/master/app/javascript/src/javascripts/autocomplete.js.erb#L76
https://github.com/e621ng/e621ng/blob/master/app/models/tag.rb#L14
Search items that are unused (eg, `disapproval:none` and `order:custom`) should be removed from the auto-completion list. Some items (such as `disapproval`) would be nice to have implemented in the future, but if it is non-functional, it should not be listed as an option.

**Comment by mm12** [comment]
Maybe its time i learn some ruby

**Comment by DonovanDMC** [comment]
> Maybe its time i learn some ruby

You don't learn ruby, you stumble through it until it works
