### ISSUE TITLE
Private vulnerability reporting

### ISSUE THREAD

**Issue by Sim4n6** [zwagoth/e621ng#533]
Hi , 

I may have identified a low-severity vulnerability in the latest codebase. 
Could you please consider enabling the [GitHub private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) for this repository?

Regards
@Sim4n6

**Comment by Earlopain** [comment]
Thank you for opening this issue, I should have enabled that feature. I'll close this one and see you over there.

**Comment by Sim4n6** [comment]
Done, thank you.
