### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by bridgebucket** [zwagoth/e621ng#562]
Followed the easy installation instructions, and I'm using a different PC on the same network to access the website. None of the images or thumbnails load, and using inspect element shows that the src for images is from localhost. Changing localhost to the local IP of the server fixes the issue and the image shows correctly. I'm aware that this is a band-aid fix, but I only plan to use this website within lan. How can I change it so all images use the server IP instead of localhost?

**Comment by faucetlol** [comment]
Change `DANBOORU_HOSTNAME` from localhost to whatever you desire in the `docker-compose.yml` file.
https://github.com/e621ng/e621ng/blob/9b8344d943d5c81047800982dae12e79414950ea/docker-compose.yml#L4

I think you can also use the `.env` file for this too, but personally never bothered.
