### ISSUE TITLE
Problem at startup

### ISSUE THREAD

**Issue by WestFoxID** [zwagoth/e621ng#628]
I have a problem running the "docker compose up" command. The error "/app/config/application.rb:24:in `require_relative': cannot load such file -- /app/config/danbooru_local_config (LoadError)" occurs in the e621ng-e621-1 module. I don't know much about docker, but judging by the error, it requires a file. After looking at the danbooru code, I found that there should be an empty file. Created such a file. After that, I received the following error "uninitialized constant Danbooru::Environment Configuration::CustomConfiguration" ->"/app/config/danbooru_default_config.rb:686:in `custom_configuration'". Can you tell me what the gap might be?

**Comment by DonovanDMC** [comment]
you haven't ran the setup, or it failed
https://github.com/e621ng/e621ng/blob/aaf1423ef8243c29268c4f3b77e4a014cd6d4b09/bin/setup#L17-L19

**Comment by WestFoxID** [comment]
I added an additional line "docker compose ru --rm SEED_POST_COUNT=100 e621 /app/bin/setup". The installation was detected with the message "I added an additional line "docker compose ru --rm SEED_POST_COUNT=100 e621 /app/bin/setup". The installation was detected with the message "Error response from the daemon: failed to create a task for the container: failed to create a task shim: OCI runtime failed to create: runc failed to create: failed to start the container process: exec: "C:/Program Files/Git/app/bin/setup": statistics C:/Program Files/Git/app/bin/setup: there is no such file or directory: unknown
"

**Comment by WestFoxID** [comment]
I was able to execute the command. However, the following problem has arisen:

psql:/app/db/structure.sql:40: ERROR:  function "posts_trigger_change_seq" already exists with same argument types
bin/rails aborted!
failed to execute:
psql --set ON_ERROR_STOP=1 --quiet --no-psqlrc --output /dev/null --file /app/db/structure.sql e621_development

Please check the output above for any errors and make sure that `psql` is installed in your PATH and has proper permissions.


Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
/app/bin/setup:8:in 'system': Command failed with exit 1: RAILS_ENV=development bin/rails db:schema:load (RuntimeError)
from /app/bin/setup:8:in 'system!'
from /app/bin/setup:27:in 'block in \<main\>'
from /usr/local/lib/ruby/3.2.0/fileutils.rb:244:in 'chdir'
from /usr/local/lib/ruby/3.2.0/fileutils.rb:244:in 'cd'
from /app/bin/setup:11:in '\<main\>'

**Comment by Earlopain** [comment]
During your previous setup attempt it seems to have not fully created the required database schema. Try starting fresh, as explained [here](https://github.com/e621ng/e621ng?tab=readme-ov-file#i-followed-the-above-instructions-but-it-doesnt-work-what-should-i-do)
