### ISSUE TITLE
SSL error connect

### ISSUE THREAD

**Issue by Karum15** [zwagoth/e621ng#629]
Hi, after reinstalling windows, I had a problem installing e621. The error is as follows:

== Preparing database ==
Created database 'e621_test'
bin/rails aborted!
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 peeraddr=172.67.21.207:443 state=error: unexpected eof while reading (OpenSSL::SSL::SSLError)
/app/db/seeds.rb:36:in 'api_request'
/app/db/seeds.rb:44:in 'import_posts'
/app/db/seeds.rb:86:in ' main '
Tasks: TOP => db:seed
(See full trace by running task with --trace)
/app/bin/setup:8:in 'system': Command failed with exit 1: RAILS_ENV=development DANBOORU_DISABLE_THROTTLES=true bin/rails db:seed (RuntimeError)
from /app/bin/setup:8:in 'system!'
from /app/bin/setup:28:in 'block in main'
from /usr/local/lib/ruby/3.2.0/fileutils.rb:244:in 'chdir'
from /usr/local/lib/ruby/3.2.0/fileutils.rb:244:in 'cd'
from /app/bin/setup:11:in 'main'
        
How can I fix this?

**Comment by Earlopain** [comment]
Setup will now ignore any errors that may occur during posts seeding
