### ISSUE TITLE
[Localhost] Loading any page takes about 25 seconds, When I try to request more than 1 request I get the error:RuntimeError in Posts#show

### ISSUE THREAD

**Issue by DearFox** [zwagoth/e621ng#642]
I was curious to try it locally.  I launched e621ng following the instructions without any problems.
 But I ran into two problems that I decided to combine in place.

When opening http://localhost:3000/ or any other page on the site, for example http://localhost:3000/posts/1, the page loading time is about 7-25 seconds.  Repeatedly requesting an already open page leads to the same result and a long wait.
 If at the time the request is processed I want to open another page (for example, when loading http://localhost:3000/posts/1 I also want to open http://localhost:3000/posts/2) then I will receive an error on the page http://localhost:3000/posts/2
![img](https://github.com/e621ng/e621ng/assets/59219907/6711cfa0-5107-487b-83bc-9241fb91b70e)
Re-requesting the page http://localhost:3000/posts/2 after loading http://localhost:3000/posts/1 solves the problem and everything loads normally (still about 25 seconds)

I'm running e621ng on Windows 10
I have 24 gigabytes of RAM and 3 cores 6 CPU threads.

**Comment by faucetlol** [comment]
I was also frequently experiencing this until I (finally) moved away from Windows.

**Comment by DearFox** [comment]
> I was also frequently experiencing this until I (finally) moved away from Windows.

Do you think the problem is Windows\WSL2 ?

**Comment by faucetlol** [comment]
> Do you think the problem is Windows\WSL2 ?

It _could_ be, though my knowledge in this area is lacking. I haven't seen anybody else complain about the same thing until now, but I think most people who actively contribute to the repo are Linux users.

Slower page load times are pretty typical for Docker with WSL2 versus native Linux, not sure if it should be this bad though. I know WSL2 has also caused me other problems in the past (like not being able to properly watch for file changes) so it wouldn't surprise me if it was to blame.

**Comment by Earlopain** [comment]
The problem is definitely with windows, it's just not very good at this.

Are you sure you are executing commands in the context of WSL? Also, WSL1 does work but has abysmal performance too so it's important that you are in fact on WSL2.

**Comment by DearFox** [comment]
> The problem is definitely with windows, it's just not very good at this.
> 
> Are you sure you are executing commands in the context of WSL? Also, WSL1 does work but has abysmal performance too so it's important that you are in fact on WSL2.

I'm not sure, I just used CMD for this.
 So I didn't run WSL2 intentionally, but as far as I understand, WSL2 is used for docker, which I already have installed.

**Comment by DonovanDMC** [comment]
that conflicting chdir error can happen on any os, I've definitely seen it on linux
I believe it's coming from multiple requests trying to generate the assets at the same time, causing a conflict

if pages are taking a long time to load (20+ seconds), the assets are most likely being rebuilt on every page load for some reason

**Comment by DearFox** [comment]
> that conflicting chdir error can happen on any os, I've definitely seen it on linux I believe it's coming from multiple requests trying to generate the assets at the same time, causing a conflict
> 
> if pages are taking a long time to load (20+ seconds), the assets are most likely being rebuilt on every page load for some reason

I don't think I changed or reconfigured anything.  I just installed it according to the instructions and it works, but it works strangely and it seems to me that it’s not correct

**Comment by Earlopain** [comment]
Just using the WSL backend is not enough. You must be inside of WSL and run docker commands there for this to not suck
