### ISSUE TITLE
Segmentation Fault when initializing test posts

### ISSUE THREAD

**Issue by Tarrgon** [zwagoth/e621ng#643]
So I was reinstalling my local clone (from this repo's master branch), but I ran into this error when running `docker compose run --rm -e SEED_POST_COUNT=100 e621 /app/bin/setup`.

This happened after executing `docker compose down -v`, `docker compose build --no-cache`

So my full commands were:
```
docker compose down -v
docker compose build --no-cache
docker compose run --rm -e SEED_POST_COUNT=100 e621 /app/bin/setup
```
![r0d13_18605 1](https://github.com/e621ng/e621ng/assets/61888458/d34f7f94-487a-4716-a456-eed15936d605)

There were a lot more lines, but my console can't log them all, and when I tried piping it out (`docker compose run --rm -e SEED_POST_COUNT=100 e621 /app/bin/setup > output.txt`) the error wasn't piped, only the other logs before it.

**Comment by Earlopain** [comment]
Well, a segfault is no good. I don't think I ever had one of these with ruby. Could you check out commit https://github.com/e621ng/e621ng/commit/0dce1e50f2b9faeffc0edb880638d85b5b33e9e4, rebuild, try again? That is before the update to ruby 3.3.1

You don't have to bother trying to get the full dump. I will not be able to do anything with that, it's more meant for the actual Ruby developers.

**Comment by Tarrgon** [comment]
It's still going, but I've gotten further than 1 post, which is further than it was previously. Will update when it either completes or fails

**Comment by Tarrgon** [comment]
Yeah, reverting to 0dce1e5 worked when I built

**Comment by Earlopain** [comment]
Can you go back to HEAD, reset your volumes, and do the seeding with setting the count to 0 so it doesn't download anything? I don't do the seeding process very often and I'm curious if the rest will work for you.

**Comment by Tarrgon** [comment]
Will do

**Comment by Tarrgon** [comment]
I set it to 0, but it still died, but this time at a different place (seemingly). Though maybe it died because it downloaded a mascot?
```
== Preparing database ==
Created database 'e621_test'
https://static1.e621.net/data/mascots/e67f0b91246775999a244d28c2d3d158.jpg
--------
Faraday::ConnectionFailed: Failed to open TCP connection to static1.e621.net:443 (execution expired)
Failure during seeding, continuing on...
--------
[BUG] Segmentation fault at 0x0000000000000028
ruby 3.3.1 (2024-04-23 revision c56cd86388) +YJIT [x86_64-linux-musl]
```

**Comment by Tarrgon** [comment]
I can try just removing
```rb
begin
  import_posts
  import_mascots
rescue StandardError => e
  puts "--------"
  puts "#{e.class}: #{e.message}"
  puts "Failure during seeding, continuing on..."
  puts "--------"
end
```

from the seeding really quick?

**Comment by Tarrgon** [comment]
Yeah, after commenting those lines out, no segfault. And `docker compose up` works as expected. The admin profile was created properly.

**Comment by Earlopain** [comment]
I did a fresh setup and it just works for me. I don't know how to help you here, sorry. Could be about the architecture maybe?

**Comment by Tarrgon** [comment]
After updating windows, docker desktop, and restarting my computer Ruby 3.3.1 seems to be working, so I'm guessing my issue arose somewhere in there.

I'd say it's probably something to do with docker desktop, somehow, since I doubt a windows update would've fixed this. But for all I know it just needed a few restarts because of some memory issues.

Important note, I did reseat my memory due to a different issue related to my GPU, which may have had an affect on fixing this problem.

**Comment by Earlopain** [comment]
Weird. Docker is not perfect, configuration on the host can affect behaviour in the container. I have had issues with the open file descriptor limit causing inexplicable hangs in programs that enumerate them.

Though I don't think anything like that would cause this, I find it more likely that any of your steps fixed this.
