### ISSUE TITLE
Enable ticket API

### ISSUE THREAD

**Issue by clragon** [zwagoth/e621ng#657]
**Is your feature request related to a problem? Please describe.**
Using third party tooling to manage tickets as part of moderation efforts is difficult because the ticket API is not enabled.

**Describe the solution you'd like**
Enable the ticket JSON API endpoint.

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://github.com/e621ng/e621ng/assets/11785085/672bd1af-ed8f-4447-b2c5-6ae9a8d47699)

**Comment by DonovanDMC** [comment]
I can bang out a pr for this if neither of you want to do it
~~This _could_ be immensely easier if tickets were only visible to their creator and moderators~~

**Comment by clragon** [comment]
that'd be very kind

**Comment by Sindrake** [comment]
This had been suggested before.
I believe, the concerns around it revolved around security. Malicious users mass-grabbing everything to look for compromising information, or maybe automatically checking if their comments or posts were reported.

I don't know if I share this concern, but it's definitely something to consider here.
Making all tickets private like @DonovanDMC suggested would solve this issue, but it would make the system a lot more opaque to users. Then again, I don't know how much we care about transparency these days.

**Comment by DonovanDMC** [comment]
> This had been suggested before. I believe, the concerns around it revolved around security. Malicious users mass-grabbing everything to look for compromising information, or maybe automatically checking if their comments or posts were reported.
> 
> I don't know if I share this concern, but it's definitely something to consider here. Making all tickets private like @DonovanDMC suggested would solve this issue, but it would make the system a lot more opaque to users. Then again, I don't know how much we care about transparency these days.

After seeing the people we have stalking tickets, and pulling out tickets to harass other users (prime example: https://discord.com/channels/431908090883997698/432280999293091872/1253870984256290876), I am a firm believer in putting heavier restrictions on ticket viewing
At bare minimum we can probably make json only work for Moderator+, not in a conventional manner but I'm sure it's possibe
