### ISSUE TITLE
Include page count in search APIs

### ISSUE THREAD

**Issue by CompanyDoormat** [zwagoth/e621ng#679]
The `posts.json` search API does not include a page count or any indication that more results are available. It'd be nice if it returned the page count.

I don't know Ruby, but it seems like the needed info is already fetched as part of doing the search, in `post_sets/post.rb`, the `posts` method. It just needs to be provided in `posts_controller.rb`'s `index` method, inside of the `format.json` block.

Other search APIs probably have this issue too, but I'm mostly concerned with the post search API.

**Comment by faucetlol** [comment]
Related: issue #228

**Comment by CompanyDoormat** [comment]
> Related: issue #228

Hm, yeah. Looks like the max page is around 750, after which it switches to previous/next buttons.

I'm a bit more concerned with finding out whether or not there is a next page, since just looking at how many posts I get back is unreliable.

**Comment by Sindrake** [comment]
As Kira said in the response to the previous issue, this _is_ doable.  
But it will require changes to the format of the API response. It's also not really a priority, unfortunately.
I can't give any promises about when / if this will happen.

**Comment by CompanyDoormat** [comment]
The format change, for JSON at least, should be easy to do - the posts array is already wrapped in an object, and adding extra fields to it for the pagination info shouldn't break anything.

If I were to submit a PR, would it be considered?
