### ISSUE TITLE
Enable Post Votes API

### ISSUE THREAD

**Issue by clragon** [zwagoth/e621ng#688]
**Is your feature request related to a problem? Please describe.**
Accessing what is voted on via the API is difficult.
To know whether a user has voted on a post, 
we must make a full post search which sends much unnecessary data and wastes resources.

**Describe the solution you'd like**
It would be nice if the API would be enabled for the post_votes page.
In tandem, normal users would need to be able to have access to this page to see their own votes only.

**Comment by Sindrake** [comment]
This is not practical and unnecessary.
