### ISSUE TITLE
Posts & blacklist not showing in older browser

### ISSUE THREAD

**Issue by RedLXIX** [zwagoth/e621ng#744]
Not sure if older browser support is getting discontinued, but for the most part posts are invisible across the board. The elements are still added but not visible: https://i.imgur.com/sWACDRz.png I also found the blacklist elements in the inspect and that's pretty much empty. This isn't happening in a newer browser, however.

<sub>(Yes, yes, I know I should be using a newer browser in general but it's not _my_ fault I hate their UIs...)</sub>

**Comment by Sindrake** [comment]
Interesting.
Which browser are you using?

**Comment by RedLXIX** [comment]
Firefox 54.

Not sure what happened, the site was working fine yesterday and to my knowledge I haven't installed anything like userscripts or anything. I also just disabled ublock & adblock as those are the only things I have installed that I would think might interfere with javascript but there wasn't any change.

**Comment by Sindrake** [comment]
Hmm. I downloaded Firefox 54.0 from the Mozilla website – and the blacklist is working just fine.
You sure that you got that specific version installed?

![Screenshot 2024-09-02 170812](https://github.com/user-attachments/assets/5aac58ee-c5a6-4234-a1a8-5bbb4acc481c)

Also, could you do me a favor, and check if there are any errors in the console?
Just press F12, and go to the "Console" tab in the section that opens.

**Comment by RedLXIX** [comment]
As far as I can tell
![image](https://github.com/user-attachments/assets/22dbe325-1f0a-40e2-86ea-51b322b81fae)

As for the console, I'm wondering if this might be the culprit?
![image](https://github.com/user-attachments/assets/d8c191bb-3c59-4229-b880-cb81cc770019)
Though I was checking earlier and that didn't seem to happen then, but maybe I wasn't noticing it properly?

**Comment by Sindrake** [comment]
Yep, that is possible.
The `replaceAll()` function only started to be supported starting with version 77. https://caniuse.com/?search=replaceAll

Your blacklist seems to have a tag with a wildcard (`*`) in it – could you try removing it and see if the problem persists?

Edit: Yup, replicated it. The issue is with the wildcard tags.
I'll see if I can fix it.

**Comment by RedLXIX** [comment]
Huh, yeah, removing the `*_vore` line and reloading started showing results again.

I'd been leaving it there because I swear wildcards in blacklists worked at one point, then I started noticing stuff like `imminent_vore` showing up (made a [post](https://e621.net/forum_topics/45826) on the forum about it, too)

Edit: And thank you for your help on this!

**Comment by Sindrake** [comment]
The blacklist never supported wildcards. That used to be a feature exclusive to [re621](https://re621.app/).
I added it to the vanilla site two weeks ago in 0a7efad27bb4c100bf9474c55d67ece191af93b2.

The fix should be in the next patch.
