### ISSUE TITLE
db/populate.rb doesnt fail or print error message if it failed to create a posting

### ISSUE THREAD

**Issue by ghost** [zwagoth/e621ng#759]
If there is a problem creating a new post on the web interface it will fail and show an error message.
For the db/populate.rb script it won't fail or print an error message and it will continue downloading posts without succeeding.

**Comment by Sindrake** [comment]
This is not really an issue. At least, not a pressing one.

The populate script exists to give you some data to use for testing.
If it fails to import a post or two... well, you can just run it again if you need more of those.
