### ISSUE TITLE
Update Mod Actions API to include values

### ISSUE THREAD

**Issue by clragon** [zwagoth/e621ng#768]
Right now the API for mod actions is essentially useless, since the `values` prop, 
which contains the necessary details to construct the mod cation, is missing.
Instead the object contains an always empty `values_old` prop.

**Comment by DonovanDMC** [comment]
This has been denied a multitude of times due to security issues with exposing it directly

**Comment by Sindrake** [comment]
To be specific, this had been denied by both Kira and Earlopain, with the justification being that older mod action entries may contain privileged information that should not be exposed this way.

I would like to have a mod action clean up at some point – a lot of entries there are redundant, pointless, or broken.  
But that is a task for later.
