### ISSUE TITLE
[Mobile view] Thumbnail captions in pool stretched to edge

### ISSUE THREAD

**Issue by eiffelwong1** [zwagoth/e621ng#781]
![image](https://github.com/user-attachments/assets/71d0b5a8-5f23-4baa-9aa7-45fccd5ddf27)

posted by user 110220m

limiting the width of the caption is mentions by other user

<img width="501" alt="image" src="https://github.com/user-attachments/assets/90799db1-03c9-4ca0-b555-da3c3b5f2dc7">

**Comment by CSDSP** [comment]
This applies to thumbnails on the profile page too.

**Comment by eiffelwong1** [comment]
ops accidentally closed it

**Comment by eiffelwong1** [comment]
completed in #796
