### ISSUE TITLE
Explicit Content and Media Embeds

### ISSUE THREAD

**Issue by ghost** [zwagoth/e621ng#816]
Most messengers and other programs utilize website embeds a lot more now than before. While it is convenient, it does cause problems in certain circumstances.

Currently, any link pasted from e621 into Discord (for example) will automatically embed and show the content. The problem with this is that not everyone in the chat will be 18+ and since it is an embed there will be no 18+ warning (which also makes that 18+ warning less useful now).

This is not a theoretical situation either. I have seen it happen before where Discord users easily send content from e621 to underaged users by merely pasting a link.

Here are some proposals I have to fix this.
**External - Utilize RTA**
Currently e621 utilizes the RTA RATING meta tag. This means it could be possible that Discord could be modified where it checks upon embedding for the RATING tag to either continue or stop the embed.

This check could be expanded to also check if the channel is set to nsfw to continue with the embed as well.

The problem with this proposal is that it depends on Discord and others to know or feel like implementing this type of functionality.

**Internal - Modify Embed Code**
The e621ng code could just be modified to not embed if the content has a rating of explicit.

The problem with this proposal is that many people in the e621 Discord rely on this functionality.

The only problem with both proposals is that pasting a static1.x.com link will just bypass this and embed anyways in most programs unless the proposed RTA check is advanced.

**Comment by faucetlol** [comment]
I don't think this is e621's problem, preventing embeds on explicit content is just going to annoy plenty of people that use it legitimately. RTA tags are provided and other platforms can do with those what they will. I'd say it could be suggested at [Discord's feedback site](https://support.discord.com/hc/en-us/community/topics) but that will obviously get nowhere.

For what it's worth I just tested it and Discord also embeds content from Pornhub and other mainstream porn websites, so e621 is far from unique with this problem.

**Comment by DonovanDMC** [comment]
Discord scans images in embeds for nsfw content and already should not display it in non-nsfw channels and filter enabled dmails if the content is detected as such
This also definitely feels very much like a "not our problem" type of issue

> I have seen it happen before where Discord users easily send content from e621 to underaged users by merely pasting a link.

This reads like a "Won't somebody think of the children!!!!" line politicians use constantly to force through bad faith changes that do nothing to protect children and inconvenience or harm everyone else

> The only problem with both proposals is that pasting a static1.x.com link will just bypass this and embed anyways in most programs unless the proposed RTA check is advanced.

They could also just.. send the file? This whole argument is incredibly weak

**Comment by ghost** [comment]
> Discord scans images in embeds for nsfw content and already should not display it in non-nsfw channels and filter enabled dmails if the content is detected as such This also definitely feels very much like a "not our problem" type of issue

It should, but it doesn't filter embeds.

> This reads like a "Won't somebody think of the children!!!!" line politicians use constantly to force through bad faith changes that do nothing to protect children and inconvenience or harm everyone else

I don't want embeds to be disabled on explicit content either and would prefer it to be done through RTA tags. I only mentioned the internal proposal in the case of being able to control it directly without relying on others to do it.

I don't see how this is a bad faith change when it is just expanding on the already present RTA tag which would keep convenience and improve keeping explicit content away from underaged users.

> They could also just.. send the file? This whole argument is incredibly weak

Files and images can be (somewhat) filtered by Discord's explicit image filter, but embeds do not get filtered.

**Comment by ghost** [comment]
> I don't think this is e621's problem, preventing embeds on explicit content is just going to annoy plenty of people that use it legitimately. RTA tags are provided and other platforms can do with those what they will. I'd say it could be suggested at [Discord's feedback site](https://support.discord.com/hc/en-us/community/topics) but that will obviously get nowhere.

Yeah I understand that. I didn't start this issue for wanting to rip out embeds and more of planning to expand on the RTA tag, but it seems people are getting the wrong idea so I will just close this issue.

> For what it's worth I just tested it and Discord also embeds content from Pornhub and other mainstream porn websites, so e621 is far from unique with this problem.

Interesting to know. Still would prefer to improve rather than to do what everyone else does.

**Comment by DonovanDMC** [comment]
> > Discord scans images in embeds for nsfw content and already should not display it in non-nsfw channels and filter enabled dmails if the content is detected as such This also definitely feels very much like a "not our problem" type of issue
> 
> It should, but it doesn't filter embeds.

Yet it does? Go paste `https://e621.net/posts/5224039` into a channel that isn't marked nsfw, it will not embed
Then paste it into an nsfw channel, it will embed

![image](https://github.com/user-attachments/assets/0f20b8ba-d67a-47eb-9dfd-c391cf769d0b)
![OnPaste 20241208-223053](https://github.com/user-attachments/assets/0a4f41d3-3679-46d1-84e5-56681cf621ce)

**Comment by ghost** [comment]
![d](https://github.com/user-attachments/assets/b7940f8b-049b-40c7-b08a-b7f2ba4c194d)

Hmm. It did work with `https://e621.net/posts/5224039`, but not with `https://e621.net/posts/2667359`
